### ISSUE TITLE
style the sidebar accoring to this css

### ISSUE THREAD

**Issue by KraXen72** [tgrosinger/advanced-tables-obsidian#216]
**Is your feature request related to a problem? Please describe.**
the sidebar is poorly styled
![image](https://user-images.githubusercontent.com/21956756/195997284-ba7dcf3d-23b9-466c-b1dd-102848c85918.png)

**Describe the solution you'd like**
style it like this:
![image](https://user-images.githubusercontent.com/21956756/195997292-1863de37-d8da-4587-b215-963728bc3c9d.png)
  
**The CSS (for reference)**  
```css
:root {
	--advanced-tables-helper-size: 28px;
}
[data-type="advanced-tables-toolbar"] .nav-header::before {
	content: "Advanced Tables";
	font-weight: var(--font-medium);
	font-size: var(--nav-item-size);
    color: var(--nav-item-color);
	text-decoration: underline;
}
[data-type="advanced-tables-toolbar"] .nav-buttons-container {
	column-gap: 0.2rem;
	margin: 0.2rem 0 0.2rem 0;
	justify-content: start;
}
[data-type="advanced-tables-toolbar"] .nav-buttons-container::before {
	min-width: 2.6rem;
	line-height: var(--advanced-tables-helper-size);
	font-size: var(--nav-item-size);
    font-weight: var(--nav-item-weight);
    color: var(--nav-item-color);
}
[data-type="advanced-tables-toolbar"] .nav-buttons-container > * {
	height: var(--advanced-tables-helper-size);
	line-height: var(--advanced-tables-helper-size);
}
[data-type="advanced-tables-toolbar"] .nav-buttons-container .nav-action-button {
	width: var(--advanced-tables-helper-size);
	height: var(--advanced-tables-helper-size);
	display: flex;
	justify-content: center;
	align-items: center;
	border-radius: var(--radius-s);
}
[data-type="advanced-tables-toolbar"] .nav-buttons-container .nav-action-button:hover{
	background-color: var(--nav-item-background-hover);
    color: var(--nav-item-color-hover);
    font-weight: var(--nav-item-weight-hover);
}

[data-type="advanced-tables-toolbar"] .nav-buttons-container:nth-child(1)::before {
	content: "align:"
}
[data-type="advanced-tables-toolbar"] .nav-buttons-container:nth-child(2)::before {
	content: "move:"
}
[data-type="advanced-tables-toolbar"] .nav-buttons-container:nth-child(3)::before {
	content: "edit:"
}
[data-type="advanced-tables-toolbar"] .nav-buttons-container:nth-child(4)::before {
	content: "sort/f:"
}
[data-type="advanced-tables-toolbar"] .nav-buttons-container:nth-child(5)::before {
	content: "misc:"
}
```

**Comment by luckman212** [comment]
Nice job @KraXen72

**Comment by tgrosinger** [comment]
This looks great, thank you.

**Comment by KraXen72** [comment]
thanks for using my snippet in the plugin! 
i added these two more lines, but it's purely preference.
```css
.advanced-tables-row-label { text-transform: lowercase; }
.advanced-tables-buttons .nav-header { padding: 4px 0; }
```
